name: CI/CD

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: ./dish-craft-web
      run: npm install

    # - name: Run the tests
    #   working-directory: ./dish-craft-web
    #   run: npm test

    - name: Build
      working-directory: ./dish-craft-web
      run: npm run build

  docker-build:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: cd into repo
        uses: actions/checkout@v3
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./dish-craft-web
          file: ./dish-craft-web/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dishcraft-web:latest

  # render-deploy:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - docker-build
  #   steps: 
  #     - name: Deploy to production
  #       uses: johnbeynon/render-deploy-action@v0.0.8
  #       with: 
  #         service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
  #         api-key: ${{ secrets.MY_RENDER_API_KEY }} 
